### ISSUE TITLE
Timeout Option for SchemaRegistryClient

### ISSUE THREAD

**Issue by snazzyfox** [confluentinc/confluent-kafka-python#905] opened 2020-06-30 19:54 UTC
Description
===========
SchemaRegistryClient does not supply a timeout to the underlying calls to `requests`. If a network issue causes no data to be returned (such as firewall/security group misconfiguration), the client will wait forever instead of raising a timeout error. This essentially causes the application to hang.

We should add a new configuration option to SchemaRegistryClient that sets the timeout so that an error may be raised/caught in these situations.

How to reproduce
================
With a blackhole server running locally, for example on port 8000

```python
from confluent_kafka.schema_registry import SchemaRegistryClient
client = SchemaRegistryClient({'url': 'localhost:8000'})
client.get_subjects()  # this will hang forever
````

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): both 1.4.2
 - [ ] Apache Kafka broker version: irrelevant
 - [ ] Client configuration: `{...}`: irrelevant
 - [x] Operating system: Probably irrelevant since schema registry client is pure python, but reproduced on ubuntu 20.04, amazon linux 2, and windows 10
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zschumacher** [comment] 2022-01-26 15:40
can we reopen this?  It is still an issue for us and probably others.

**Comment by jliunyu** [comment] 2022-02-01 22:46
We are looking into this issue.

**Comment by slominskir** [comment] 2022-04-27 23:01
Duplicate of https://github.com/confluentinc/confluent-kafka-python/issues/622

**Comment by chipola** [comment] 2024-03-27 22:12
It looks like there's a PR submitted, can we get someone from the team to take a look? cc: @jliunyu

**Comment by rayokota** [comment] 2024-12-12 16:12
Fixed by https://github.com/confluentinc/confluent-kafka-python/pull/1852

**Closed by rayokota** 2024-12-12 16:12 UTC
Labels: enhancement, schema registry
