### ISSUE TITLE
Timed out metadataRequest in flight was not catched by callback of execption

### ISSUE THREAD

**Issue by dfhyr123** [confluentinc/confluent-kafka-python#982] opened 2020-11-10 16:16 UTC
Description
===========
Hi our kafka has crashed for about 2 days, while that one of our producers using confluent kafka for python still tried producing a messages and while that we received logs that say `Timed out MetadataRequest in flight` and `Metadata request failed: periodic topic and broker list refresh: Local: Host Resolution failure
`
Now our problem is that the producer didn't catch those errors like any other callback and exception and it got stuck like that until we restarted the producer.

Can you help us find why it didn't catch those logs like any other logs we are using callback on delivery and error_cb and every function is wrapped with exceptions.

Also what caused this error we didn't get this error till now.

Also maybe you know how we can reproduce this error so we can try to debug it on our on,

Thanks!

How to reproduce
================
I think its a  network error I don't know how to reproduce

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):python -   confluent_kafka - 1.4.1 ,libversion - 1.4.0
 - [X] Apache Kafka broker version: 2.2.0
 - [X] Client configuration: `{...}`
 - [X] Operating system: RHEL
 - [X] Provide client logs (with `'debug': '..'` as necessary) `Timed out MetadataRequest in flight` and `Metadata request failed: periodic topic and broker list refresh: Local: Host Resolution failure
`
 - [X] Provide broker log excerpts
 - [X] Critical issue: couldn't recover from crash

**Comment by edenhill** [comment] 2020-11-10 17:13
Looks like you hit a regression in librdkafka v1.3.0 which is fixed in v1.4.2
Please upgrade your Python client to v1.5.0.

https://github.com/edenhill/librdkafka/releases/tag/v1.4.2

**Closed** 2021-01-26 14:22 UTC
