### ISSUE TITLE
Automatically destory/recreate consumer client when connection is stale

### ISSUE THREAD

**Issue by tatianafrank** [confluentinc/confluent-kafka-python#899] opened 2020-06-17 19:00 UTC
Description
===========
I have a script that runs an infinite while loop that continually consumes messages from a kafka topic using v1.4 of the confluent-kafka library. Sometimes, either due to too many connection timeout errors or some unknown issue, I will need to stop/restart the entire script so that the kafka client object can be destroyed/recreated and start working again. My question is if there is a dynamic way to detect when the client object needs to be recreated in the code without having to manually detect, stop, restart the entire script. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.4.0
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment] 2020-06-19 17:19
Intended behavior is the client should automatically recover from all problems where it's possible to do so. If it doesn't then there's a bug. I'm not 100% sure if there's any known outstanding issues related to this (there doesn't seem to be any related fixes post 1.4.0 in the librdkafka release notes). Any more information you can provide would be appreciated (debug logs, though they are very verbose, so difficult to get in prod if this is a very intermittent issue).
cc: @edenhill

**Comment by edenhill** [comment] 2020-07-07 11:05
This might be "produce/consume hang after partition goes away and comes back, such as when a topic is deleted and re-created." which is fixed in v1.4.2:
https://github.com/edenhill/librdkafka/blob/master/CHANGELOG.md#librdkafka-v142

**Comment by tatianafrank** [comment] 2020-07-08 19:22
ok I deployed 1.4.2 so hopefully that helps.. Ill have to wait and see if the issue appears again

**Comment by holyachon** [comment] 2020-07-20 07:27
@tatianafrank hello. I think i have the same issue in v1.4.2. Does the issue be fixed after version up?

**Comment by tatianafrank** [comment] 2020-07-22 21:11
Saw this error a few times before the connection went stale again 
`ERROR: Consumer error: KafkaError{code=_TRANSPORT,val=-195,str="FindCoordinator response error: Local: Broker transport failure"}`
Our kafka topic was down and then it was rebooted but instead of the service using confluent client going back to working on its own we had to restart the service because the consumer just stopped trying to connect.

**Closed** 2021-01-26 14:49 UTC
Labels: investigate further
