### ISSUE TITLE
flush() does not work in sync way

### ISSUE THREAD

**Issue by elizabethhong** [confluentinc/confluent-kafka-python#507] opened 2018-12-12 04:24 UTC
Description
===========

In documentation, it says `Wait for all messages in the Producer queue to be delivered.` However, flush() does not block anything.

How to reproduce
================
The code is like
`for i in range(100): 
   producer.produce("message")
 producer.flush()
`
When the command is executed and exits quickly, nothing is produced. However, if sleep is added at the end, it produces random number of messages. It seems flush() does not block until all messages are actually delivered.

Checklist
=========
Please provide the following information:

 - [0.11.5] confluent-kafka-python and 
-  [0.11.4] librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [0.9.x ] Apache Kafka broker version:
 - [ ] Client configuration: `{bootstrap.servers': 'some-legit-kafka-broker-ip:9092', 'api.version.request': True, 'log.connection.close': False, 'retries': 5, 'message.timeout.ms': 30000, 'produce.offset.report': True, 'max.in.flight.requests.per.connection': 1, 'default.topic.config': {'acks': 'all'}`
 - [ ] Operating system: Ubuntu 14.04.5 LTS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by elizabethhong** [comment] 2019-01-08 06:02
Thanks for the reply!
It's not easy to bump broker version for us. Is this a known problem? Any information will be appreciated.

**Comment by edenhill** [comment] 2019-01-08 08:09
I meant the confluent-kafka-python version v0.11.6 or preferably v1.0.0-rc4

**Comment by Recodify** [comment] 2019-02-27 18:07
I can confirm this is still happening on v0.11.6 not tried v1.0.0-rc4 yet

**Comment by edenhill** [comment] 2019-03-04 08:05
Thanks for verifying the fix @Recodify , closing this issue.

**Closed by edenhill** 2019-03-04 08:05 UTC

**Comment by amitt001** [comment] 2019-03-04 20:34
@edenhill is there a currently a way to have a blocking/sync flush? Tested it with v0.11.6 and some old versions also and flush is async.

 v1.0.0-rc4 is failing with 

> confluent_kafka/src/confluent_kafka.c:1222:20: error: use of undeclared identifier 'RD_KAFKA_RESP_ERR__FATAL'; did you mean 'RD_KAFKA_RESP_ERR__FAIL'?

@Recodify ^

**Comment by edenhill** [comment] 2019-03-04 20:43
You will need to install librdkafka from source (master branch) until v1.0.0 has been released (aprox 2w)

**Comment by amitt001** [comment] 2019-03-04 20:54
@edenhill thanks. Successfully installed it but still seeing the same behavior. Code finishes but messages still streaming to Kafka

confluent-kafka==1.0.0rc4

code:
```
from confluent_kafka import Producer
producer = Producer({'bootstrap.servers': 'kafka-1:19092,kafka-2:29092,kafka-3:39092',
    'default.topic.config': {'acks': 'all'}})

ss = '0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100101102103104105106107108109110111112113114115116117118119120121122123124125126127128129130131132133134135136137138139140141142143144145146147148149150151152153154155156157158159160161162163164165166167168169170171172173174175176177178179180181182183184185186187188189190191192193194195196197198199200201202203204205206207208209210211212213214215216217218219220221222223224225226227228229230231232233234235236237238239240241242243244245246247248249250251252253254255256257258259260261262263264265266267268269270271272273274275276277278279280281282283284285286287288289290291292293294295296297298299300301302303304305306307308309310311312313314315316317318319320321322323324325326327328329330331332333334335336337338339340341342343344345346347348349350351352353354355356357'

def f():
    import time
    start = time.time()
    for i in xrange(100000):
        #try:
            producer.produce('test-topic', ss)
        #except Exception:
            #producer.poll(0)
            #try:
            #    producer.produce('test-topic', ss)
            #except Exception:
            #    producer.flush(0)
        #producer.poll(0)
    producer.flush(30)
    print(time.time() - start)


if __name__ == '__main__':
    f()
```

**Comment by edenhill** [comment] 2019-03-04 21:05
Can you time the flush() call, and also print len(producer) before and after flush()?

**Comment by amitt001** [comment] 2019-03-04 21:13
len(producer): 100016
Flush time: 1.37350106239
Post flush len(poducer): 0
Total time: 1.73393011093

(This 100016, extra 16 messages, is strange ans it's chnaging to 100003, 100009 etc)

**Comment by edenhill** [comment] 2019-03-04 21:42
The length also includes other queue events, so it should just be used as a rough estimate.
But look at that output it seems to work as expected, it takes 1.3s to flush the 100k messages; that is, produce them to the broker, or fail them. Since you dont have an on_delivery callback on the producer you dont know if the delivery succeeded or not.

**Comment by amitt001** [comment] 2019-03-04 21:49
@edenhill I am running a kafkacat client on other terminal and I can see all the messages finally reach to the queue. It takes 6-7 seconds after the python script ends for all the messages to stream completely. I can see that all the messages are getting delivered without any loss.

I have also tested native Java producer with acks = all and it actually waits for all the message to finish. It finishes exactly with kafkacat application(I can share the source code if required)

So I am wondering if there is an internal queue that's keeping the messages but replying with success even though messages haven't actually reached to the broker?

**Comment by edenhill** [comment] 2019-03-04 22:14
That does sound weird.. when len(producer) reaches zero there are no more messages in the producer, theyre all delivered.

**Comment by amitt001** [comment] 2019-03-05 07:17
Yes sounds right and it doesn't make any sense why acks=all is performing like this. Maybe I am missing something?
Made a screen capture video showing this https://imgur.com/LiDx110

I think this should be reproducible. I am using confluent-kafka "confluentinc/cp-kafka:latest" docker image with 3 zookeeper and 3 kafka brokers

```
Metadata for test-topic (from broker 2: kafka-2:29092/2):
 3 brokers:
  broker 2 at kafka-2:29092
  broker 3 at kafka-3:39092
  broker 1 at kafka-1:19092
 1 topics:
  topic "test-topic" with 1 partitions:
    partition 0, leader 2, replicas: 2, isrs: 2
```

**Comment by edenhill** [comment] 2019-03-05 07:54
I think the 6-7 delay is because of it takes that long for the terminal to print all the messages.
My guess is that if you instead pipe kafkacat to `wc` it will be much faster.

**Comment by amitt001** [comment] 2019-03-05 08:11
Yes, that's the reason for this. Thanks! @edenhill

I am trying to compare apache Kafka with librdkafka. In my tests java producer is much much slower(8-9x) than Python's confluent-Kafka. I see librdkafka performance in "INTRODUCTION" and it's impressive.

Is there a benchmark done on this? I couldn't find anything comparing both on the same machine config.

**Comment by edenhill** [comment] 2019-03-05 08:24
General benchmarks are indicative at best, you will need to perform benchmarks using your environment, your data sets, sizes and rates, to get meaningful values.

The most important configuration for tuning performance vs latency is the `linger.ms` property, a higher value will promote larger batches and higher thruput and the expense of higher latency.
Good initial values to try are in the range of 5..50ms depending on your produce rate.
