### ISSUE TITLE
Regression: confluent-kafka 2.6.0 can't connect to redpanda cluster

### ISSUE THREAD

**Issue by maver1ck** [confluentinc/confluent-kafka-python#1846] opened 2024-11-12 12:13 UTC
Description
===========

I'm upgraded confluent-kafka from 2.5.0 to 2.6.0. This breaks communication with redpanda.

How to reproduce
================

I'm using following code.

Redpanda is deployed on Kubernetes using helm chart.

```
from confluent_kafka import Consumer, KafkaException
import sys

def create_consumer():
    # Configure the consumer
    conf = {
        'bootstrap.servers': 'redpanda.redpanda.svc:9093',
        'group.id': 'python-consumer-group',  # Consumer group ID
        'auto.offset.reset': 'earliest',  # Equivalent to --from-beginning
	# 'debug': 'fetch,metadata,topic,broker'
    }

    # Create Consumer instance
    consumer = Consumer(conf)
    return consumer

def consume_messages():
    consumer = create_consumer()

    try:
        # Subscribe to topic
        consumer.subscribe(['dwh-events'])

        # Continuous loop to consume messages
        while True:
            try:
                # Poll for messages with a timeout of 1.0 second
                msg = consumer.poll(1.0)

                if msg is None:
                    continue

                if msg.error():
                    raise KafkaException(msg.error())

                # Process the message
                print(f"Topic: {msg.topic()}")
                print(f"Partition: {msg.partition()}")
                print(f"Offset: {msg.offset()}")
                print(f"Key: {msg.key().decode('utf-8') if msg.key() else 'None'}")
                print(f"Value: {msg.value().decode('utf-8')}")
                print("-------------------")

            except KeyboardInterrupt:
                break

    finally:
        # Close down consumer to commit final offsets.
        consumer.close()

if __name__ == "__main__":
    try:
        consume_messages()
    except KeyboardInterrupt:
        sys.stderr.write('\nStopped by user\n')
    except Exception as e:
        sys.stderr.write(f'Error: {str(e)}\n')
```

2.5.0
```
(.venv) root@ubuntu:/# python consumer.py
Topic: dwh-events
Partition: 0
Offset: 0
Key: None
Value: {"data": {"message": "File uploaded successfully"}, "metadata": {"s3_metadata": {"file_path": "s3://your_bucket/your_file.parquet"}, "file_info": {"table_name": "your_table_name"}}}
```

2.6.0
```
(.venv) root@ubuntu:/# python consumer.py
%6|1731410803.685|FAIL|rdkafka#consumer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 4ms in state UP)
%6|1731410804.193|FAIL|rdkafka#consumer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 438ms in state UP, 1 identical error(s) suppressed)
%6|1731410837.531|FAIL|rdkafka#consumer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 30ms in state UP, 8 identical error(s) suppressed)
%6|1731410876.407|FAIL|rdkafka#consumer-1| [thrd:redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0]: redpanda-0.redpanda.redpanda.svc.cluster.local.:9093/0: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 8ms in state UP, 4 identical error(s) suppressed)
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 2.6.0
 - [x] Apache Kafka broker version: redpanda:v23.3.6
 - [x] Client configuration: described in code
 - [x] Operating system: tested on MacOS 15.1 and Ubuntu 24.04
 - [x] Provide client logs (with `'debug': '..'` as necessary) - logs attached
 - [x] Provide broker log excerpts
 - [ ] Critical issue

Client log:
[redpanda.txt](https://github.com/user-attachments/files/17716292/redpanda.txt)

Redpanda log:
WARN  2024-11-12 11:26:43,685 [shard 1:main] kafka - connection_context.cc:310 - Error while processing request from 10.224.5.138:60184 - Unsupported version 12 for fetch API

**Comment by pranavrth** [comment] 2024-11-13 08:13
This is duplicate of https://github.com/confluentinc/confluent-kafka-python/issues/1842. We plan to release the fix next week. Closing this.

**Closed by pranavrth** 2024-11-13 08:13 UTC
