### ISSUE TITLE
Seg-fault in running integration test

### ISSUE THREAD

**Issue by tejasbehra** [confluentinc/confluent-kafka-python#89] opened 2016-11-28 15:03 UTC
('==============================', 'Verifying Producer', '==============================')
producer at <cimpl.Producer object at 0x7f86f7d7e808>
Waiting for 16 messages to be delivered
Message delivered to test [0] at offset [17]: This one has a dr callback
Message delivered to test [0] at offset [18]: This one has a lambda
Message delivered to test [0] at offset [20]: Message #0
Message delivered to test [0] at offset [21]: Message #1
Message delivered to test [0] at offset [22]: Message #2
Message delivered to test [0] at offset [23]: Message #3
Message delivered to test [0] at offset [24]: Message #4
Message delivered to test [0] at offset [25]: Message #5
Message delivered to test [0] at offset [26]: Message #6
Message delivered to test [0] at offset [27]: Message #7
Message delivered to test [0] at offset [28]: Message #8
Message delivered to test [0] at offset [29]: Message #9
('==============================', 'Verifying Consumer', '==============================')
Traceback (most recent call last):
  File "integration_test.py", line 464, in <module>
    verify_consumer()
  File "integration_test.py", line 258, in verify_consumer
    tstype, timestamp = msg.timestamp()
AttributeError: 'cimpl.Message' object has no attribute 'timestamp'
Segmentation fault (core dumped)

**Comment by edenhill** [comment] 2016-11-28 15:12
Duplicate of #81:
You are must likely running the tests using an older installed confluent_kafka version
Message.timestamp was added in 0.9.2

**Closed by edenhill** 2016-11-28 15:12 UTC
