### ISSUE TITLE
Consumer.committed() hangs if kafka broker dies

### ISSUE THREAD

**Issue by johnrgregg3** [confluentinc/confluent-kafka-python#162] opened 2017-03-24 17:18 UTC
In my main polling loop, if I call Consumer.committed(TopicPartitionList), this will hang forever if the kafka broker goes down (ALL_BROKERS_DOWN event). I think it even might happen if some brokers are still up but all brokers(s) that have my partitions went down.

I am a version behind, however:
confluent_kafka.version() ('0.9.2', 590080), confluent_kafka.libversion() ('0.9.3', 590847)

**Comment by ewencp** [comment] 2017-03-25 06:44
@johnrgregg3 This API call queries Kafka for committed offsets. This works through the consumer group protocol, so the request needs to go to the broker that is the group coordinator for the group you are requesting offsets for. This is determined internally in Kafka based on the leader of the topic partition of the __consumer_offsets topic that handles this group's metadata. What this means is that if all brokers are down, then there is no way to resolve this query since it requires a broker to be up to answer the query at all. So if you're testing against a single node cluster, you'll be stuck if no brokers are up.

If you have a partial outage of brokers, the behavior depends on which brokers fail. If some brokers fail but there is still a replica for the relevant topic partition of __consumer_offsets, then it should take over leadership and be able to respond to this query. However, if all replicas for the relevant topic partition go offline, then the data needed to respond to the query simply wouldn't be available and so we could not answer it.

I think this explanation to your question means that this isn't really a bug, but since you say it hangs if the broker dies, it's probably worth clarifying -- does it hang forever even when you've provided a timeout to the `Consumer.committed()` method? Or does it timeout in that case? If we're not properly respecting a timeout when the request needs to fail due to the required brokers not being available, then that's definitely a bug.

**Comment by johnrgregg3** [comment] 2017-03-27 19:11
It looks like even when I use the timeout argument, the underlying request obeys it (I start seeing stats callbacks and stuff after the timeout expires), but my actual call to committed() still never returns.

**Comment by edenhill** [comment] 2017-03-27 19:14
>  this will hang forever if the kafka broker goes down 

are the brokers down prior to calling committed() or while you call it?

**Comment by johnrgregg3** [comment] 2017-03-27 21:48
The brokers are already down at the time I call it. It would be hard to set up a test where the brokers went down at the very moment I called committed().

**Comment by edenhill** [comment] 2017-08-09 13:26
Can't reproduce with confluent-kafka-python 0.11.0 and librdkafka 0.11.0:

```
3|1502285121.868|FAIL|rdkafka#consumer-2| [thrd:localhost:62054/bootstrap]: localhost:62054/2: Receive failed: Disconnected
%3|1502285121.868|ERROR|rdkafka#consumer-2| [thrd:localhost:62054/bootstrap]: localhost:62054/2: Receive failed: Disconnected
%3|1502285121.868|ERROR|rdkafka#consumer-2| [thrd:localhost:62054/bootstrap]: 3/3 brokers are down
%5|1502285121.868|FAIL|rdkafka#consumer-2| [thrd:localhost:62054/bootstrap]: localhost:62054/2: Connection closed
%3|1502285121.868|ERROR|rdkafka#consumer-2| [thrd:localhost:62054/bootstrap]: localhost:62054/2: Connection closed
%3|1502285121.973|FAIL|rdkafka#consumer-2| [thrd:localhost:62054/bootstrap]: localhost:62054/2: Connect to ipv6#[::1]:62054 failed: Connection refused
%3|1502285121.973|ERROR|rdkafka#consumer-2| [thrd:localhost:62054/bootstrap]: localhost:62054/2: Connect to ipv6#[::1]:62054 failed: Connection refused
c.committed([TopicPartition('test',1)], timeout=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed to get committed offsets: Local: Timed out"}
```

**Closed by edenhill** 2017-08-09 13:26 UTC
Labels: tryreproduce
