### ISSUE TITLE
Memory leak from Producer

### ISSUE THREAD

**Issue by oranb** [confluentinc/confluent-kafka-python#543] opened 2019-02-20 12:24 UTC
Description
===========
Experiencing memory leak on Kafka producer simple application.
Application starts from around 20MB and can get to even 8G of RAM after few days.

Producer queue is empty, and poll is being called on regular basis.

Using objgraph and heapy it seems that the root cause for the leak is not from the code who wraps confluent_kafka
 
delivery.report.only.error is not set to true as described in https://github.com/confluentinc/confluent-kafka-python/issues/84 as possible cause for memory leak.

How to reproduce
================
Memory is getting bigger gradually over time depending on the size of the data which being sent.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 0.11.5 for confluent-kafka-python, 0.11.6 for librdkafka
 - [x] Apache Kafka broker version: 1.0.1
 - [x] Client configuration: `{
		"acks": 1,
		"linger.ms": 100,
		"request.timeout.ms": 300000,
		"retries": 50
	}` 
 - [x] Operating system: Ubuntu 14.04 trusty
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2019-02-20 13:01
You are most likely hitting https://github.com/confluentinc/confluent-kafka-python/pull/525

**Comment by oranb** [comment] 2019-02-20 13:34
Thanks for the quick response.

Does https://github.com/confluentinc/confluent-kafka-python/pull/525 cause leaks even if there are no errors? The leaks happening regardless of errors.

How can it be workaround before taking fix version? only not using the delivery report?

**Comment by oranb** [comment] 2019-02-20 17:10
Update - After farther checking it seems root cause was found.

The leak is due to message headers. Without adding headers to messages on produce(), there is no leak.

Seems related to https://github.com/confluentinc/confluent-kafka-python/pull/458/commits only it was fixed for 0.11.6, no? I'm using 0.11.6 and it still occurs.

**Comment by edenhill** [comment] 2019-03-11 08:39
The headers memory leak shouldve been fixed in 0.11.6, unless there is another issue.

Can you provide a small reproducible program?

**Comment by edenhill** [comment] 2019-04-09 14:00
@oranb Can you provide a small reproducible program?

**Comment by rnpridgeon** [comment] 2019-07-18 21:04
Closing for now due to inactivity. Please reopen with a reproducible application if the issue continues with v1.1.0

**Closed by rnpridgeon** 2019-07-18 21:04 UTC
