### ISSUE TITLE
Topic with 2 partitions, using a single consumer not getting all messages

### ISSUE THREAD

**Issue by JohnOmernik** [confluentinc/confluent-kafka-python#187] opened 2017-05-03 20:53 UTC
Hello, I am using the high level consumer here, and I made (perhaps wrongly) an assumption that if I have multiple partitions, but only use a single consumer instance in a group, that that instance will get all messages from all partitions. 

If I add an instance to the group, then kafka will rebalance the partitions between my instances. 

This has been the case with other libraries with Python that I've used.  

However, it seems with this library, only one partition is being consumed... is this normal? Do I need to set something to ensure it gets all messages?

**Comment by edenhill** [comment] 2017-05-03 21:10
Your expectation is correct, a single consumer in a group with no other consumers will be assigned all partitions for the subscribed topics and I'm surprised it isn't working for you.

Can you provide some code samples where you set up the consumer?

**Comment by JohnOmernik** [comment] 2017-05-03 21:38
Hmm, looking at another issue. I wonder if the issue has to do with expired data in the partition, and then when new data is added, when set to earliest, it can't find those earlier messages, and thus never starts moving forward... I cleared my topic, and now have things working correctly. It still bothers me that it was showing as lag on those partitions.  I will keep an eye out for things going forward.

**Comment by smal** [comment] 2017-05-15 13:47
Hi, 

I can confirm, that this issue exists in the latest confluent kafka.
My system:

```
Linux staging 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
Installed confluent kafka and librdkafka
```

aptitude show confluent-kafka-2.11   
Package: confluent-kafka-2.11            
New: yes
State: installed
Automatically installed: no
Version: 0.10.2.0-1

aptitude show librdkafka1
Package: librdkafka1                     
State: installed
Automatically installed: no
Multi-Arch: same
Version: 0.9.4~1confluent3.2.0-1

```

Created topic with two partitions
```
kafka-topics --create --zookeeper localhost:2181 --topic clicks --partitions 2 --replication-factor 1
```

65 elements were send to the topic.

Try to get messages with confluent-kafka consumer in python shell

```
In [1]: from confluent_kafka import Consumer
In [2]: c = Consumer({'bootstrap.servers': 'localhost:9092', 'group.id': 'confluent-client', 'default.topic.config': {'auto.offset.reset': 'smallest'}, 'api.version.request': True})
In [3]: c.subscribe(['clicks'])

In [4]: cnt = 0

In [5]: while True:
    ...:     msg = c.poll(timeout=0.1)
    ...:     if not msg:
    ...:         break
    ...:     print msg.value()
    ...:     cnt +=1
    ...:     

In [6]: cnt
Out[6]: 25
```

Get messages with kafka-python from python shell

```
In [7]: from kafka import KafkaConsumer

In [8]: consumer = KafkaConsumer('clicks', group_id='kafka-python-client', bootstrap_servers=['localhost:9092'], auto_offset_reset='smallest')

In [9]: cnt = 0 

In [10]: for msg in consumer:
    ...:     print msg
    ...:     cnt += 1
    ...:     

In [11]: cnt
Out[11]: 65
```

With single partition topic, confluent consumer receives all messages in the topic and everything works perfectly.

I think, confluent consumer receives only messages from the first partition, while others partitions are missed in poll.
Can you suggest how to fix it or at least confirm this bug? 
Maybe, you can suggest kafka/consumer log to figure out reasons of that behaviour?

Thanks in advance

**Comment by edenhill** [comment] 2017-05-15 14:26
@smal Are you sure there are no previous offsets committed for the given partitions and group ("confluent-client")?

Could you print the assignment, by adding these lines:

```
    def print_assignment(consumer, partitions):
        print('Assignment:', partitions)

    # Subscribe to topics
    c.subscribe(['clicks'], on_assign=print_assignment)
``

**Comment by smal** [comment] 2017-05-15 15:41
@edenhill , yes, I'm sure,  because I have made few tests within newly-created topic, as well as with a new group_id.

I have deleted and created topic again.
```
$ kafka-topics --zookeeper localhost:2181 --topic clicks --delete               
Topic clicks is marked for deletion.
Note: This will have no impact if delete.topic.enable is not set to true.

$ kafka-consumer-groups --bootstrap-server localhost:9092 --list
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).

$ kafka-topics --create --zookeeper localhost:2181 --topic clicks --partitions 2 --replication-factor 1

Created topic "clicks".

$ kafka-consumer-groups --bootstrap-server localhost:9092 --list                                       
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).

```

Produced 65 entries
```
kafka-run-class kafka.tools.GetOffsetShell --broker-list localhost:9092 --topic clicks          
clicks:1:32
clicks:0:33
```

And again, in python shell received only 33 items (from partition 0), but both partitions were assigned to consumer
```
In [1]: from confluent_kafka import Consumer

In [2]: def print_assinment(consumer, partitions):
   ...:     print "Assignment: ", partitions
   ...:     

In [3]: c = Consumer({'bootstrap.servers': 'localhost:9092', 'group.id': 'confluent-client', 'default.topic.config': {'auto.offset.reset': 'smallest'}, 'api.version.request': True})
   ...: 

In [4]: c.subscribe(['clicks'], on_assign=print_assinment)

In [5]: cnt = 0

In [6]: while True:
   ...:     msg = c.poll(0.1)
   ...:     if not msg:
   ...:         break
   ...:     print msg.value()
   ...:     cnt += 1
   ...:     
Assignment:  [TopicPartition{topic=clicks,partition=0,offset=-1001,error=None}, TopicPartition{topic=clicks,partition=1,offset=-1001,error=None}]

In [7]: cnt
Out[7]: 33
```

Console command shows me details for `confluent-client` consumer group looks like partition#1 wasn't consumed at all.
```
$ kafka-consumer-groups --bootstrap-server localhost:9092 --group confluent-client --describe
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).


TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG        CONSUMER-ID                                       HOST                           CLIENT-ID
clicks                         0          33              33              0          rdkafka-ce331169-6e48-4d29-9f94-8b81f5384d1e      /127.0.0.1                     rdkafka
clicks                         1          -               32              -          rdkafka-ce331169-6e48-4d29-9f94-8b81f5384d1e      /127.0.0.1                     rdkafka
```

**Comment by edenhill** [comment] 2017-05-15 15:58
```¨
           msg = c.poll(0.1)
   ...:     if not msg:
   ...:         break
```

I think this piece of code is the problem: if there is no message showing up for 100ms you'll exit the loop.
I suggest using some other means of knowing when to exit, e.g., message count, end of partition, KeyboardInterrupt, etc.
Also, since errors are signaled through poll() as messages with an error code set you need to make sure to check msg.error() and then dont treat that as a proper message but rather an error or informative (e.g., PARTITION_EOF) event.

Here's an example:
https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/consumer.py#L88

**Comment by smal** [comment] 2017-05-16 10:44
@edenhill , yeah, you're right and I've missed that thing, the problem was in my code. Everything works as expected, thanks.

**Comment by edenhill** [comment] 2017-05-16 10:50
Glad to hear that!

**Closed** 2017-05-18 12:17 UTC

**Comment by rohitgcs** [comment] 2018-02-22 19:29
Hi @edenhill I have the same issue.
I have a topic with 75 partitions and I tried one consumer with the on_assign function to display partitions.
The partitions show up in the output and it starts consuming from some threads but not from the other.


```
def main():
        consumerConfig = {
                'bootstrap.servers': KAFKA_BROKER, 
                'group.id': 'bullktest',
                'client.id':'bulk',
                'enable.auto.commit': True,
                'auto.commit.interval.ms':1000,
                'default.topic.config':
                {
                                'auto.offset.reset': 'earliest'
                }
        }
        consumer = Consumer(**consumerConfig)
        consumer.subscribe([FROM_TOPIC], on_assign=print_assignment)  
        main(consumer)
```

```
('Assignment:',
 [TopicPartition{topic=stg_gcdb_shipment_summary,partition=0,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=1,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=2,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=3,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=4,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=5,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=6,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=7,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=8,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=9,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=10,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=11,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=12,offset=-1001,error=None},
... omitted lines in between ...
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=69,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=70,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=71,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=72,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=73,offset=-1001,error=None},
 TopicPartition{topic=stg_gcdb_shipment_summary,partition=74,offset=-1001,error=None}])
```
![screen shot 2018-02-22 at 11 11 57 am](https://user-images.githubusercontent.com/31675370/36559728-a5c9850a-17c3-11e8-9b0b-1eabaaf61aa8.png)

**Comment by edenhill** [comment] 2018-02-22 19:54
Is it possible that partitions 1,2,12, etc are empty (due to retention)?
librdkafka will currently only commit offsets for messages it has seen, not when it reaches the end of a partition without seeing any messages.

**Comment by rohitgcs** [comment] 2018-02-22 20:25
@edenhill Thanks for the quick reply. But I recently loaded 200,000 new records, so something should show up when I consume right?

**Comment by edenhill** [comment] 2018-02-22 20:32
Yeah, definitely.

Is your per-message processing time high?
If so, it could be that with 75 partitions and a large number of messages in each partition, that your consumer is still trying to catch up, and the way messages are fetched in batches is that the consume fetchq (which your application is reading from with poll()) looks something like this:
 [2000msgs from partition1][2000 msgs from partition2][1500 messages from partition3][...]and so on

**Comment by rohitgcs** [comment] 2018-02-23 00:27
@edenhill Yeah, I think you're right. I see more and more partitions get a lag after some time.
So here's a question - does the consumption rate increase if the proportion of partitions to consumers are smaller.

eg: Which is faster? 75 partitions - 5 consumers, or 10 partitiosn with 5 consumers?

**Comment by edenhill** [comment] 2018-02-23 06:58
The number of partitions doesn't really matter, the processing rate is limited by the number of consumers.

**Comment by DSMP** [comment] 2018-09-21 05:48
Not exactly edenhill, If u create 10 partitions and 15 consumers. The 5 Consumers will be bored.
