### ISSUE TITLE
AvroProducer not functioning

### ISSUE THREAD

**Issue by idarlington** [confluentinc/confluent-kafka-python#221] opened 2017-07-15 06:54 UTC
I compiled librdkafka 0.9.5 on a raspberry(ARMv7 Processor rev 5 (v7l)) and I am using confluent-kafka-python 0.9.4.

I notice that an avroproducer python code runs without any errors but I don't get the message on the avro consumer console. 

I tried this on a 64 bit laptop and it works fine.

@edenhill Is this a problem with the processor type?

**Comment by edenhill** [comment] 2017-07-15 08:12
Interesting, could you enable `'debug': 'fetch,cgrp'` and provide us the logs to troubleshoot this issue?

**Comment by idarlington** [comment] 2017-07-15 08:18
Thanks @edenhill .

This is the output:

```
%7|1500106646.811|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance
%7|1500106646.811|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
%7|1500106646.811|DESTROY|rdkafka#producer-1| [thrd:main]: Removing all topics

```

**Comment by edenhill** [comment] 2017-07-15 08:21
That's all the output you get?!
Can you provide your client code? (especially around Consumer creation and message consumtion)

**Comment by idarlington** [comment] 2017-07-15 09:13
This is the producer similar to  the example code:
```
from confluent_kafka import avro
from confluent_kafka.avro import AvroProducer

schema = avro.load('stream.avsc')
value = {'data': [{'powerSinceLast': [{'sourceName': u'MUST4024C', 'powerSinceLast': 922.20799999999986, 'sourceType': u'inverter', 'configID_FK': u''}, {'sourceName': u'PERKINSP40P3', 'powerSinceLast': 0.0, 'sourceType': u'generator', 'configID_FK': u''}, {'sourceName': u'EKODISCO', 'powerSinceLast': 7340.7756799999988, 'sourceType': u'grid', 'configID_FK': u''}], 'costSinceLast': [{'sourceName': u'MUST4024C', 'sourceType': u'inverter', 'costSinceLast': 0.0, 'configID_FK': u''}, {'sourceName': u'PERKINSP40P3', 'sourceType': u'generator', 'costSinceLast': 0, 'configID_FK': u''}, {'sourceName': u'EKODISCO', 'sourceType': u'grid', 'costSinceLast': 0.25651667851977877, 'configID_FK': u''}], 'activeSource': [{'sourceName': u'EKODISCO', 'sourceType': u'grid', 'configID_FK': u'G1OKQR2XWWH5DZFY3Z4MCUTXIAEZ1OJF'}], 'energyTodaySource': [{'sourceName': u'MUST4024C', 'energyToday': 16600.828147779626, 'sourceType': u'inverter', 'configID_FK': u''}, {'sourceName': u'PERKINSP40P3', 'energyToday': 106.78621034655752, 'sourceType': u'generator', 'configID_FK': u''}, {'sourceName': u'EKODISCO', 'energyToday': 62256.536771018938, 'sourceType': u'grid', 'configID_FK': u''}], 'voltage': [{'sourceName': u'MUST4024C', 'sourceType': u'inverter', 'value': [230.0, 0, 0], 'configID_FK': u''}, {'sourceName': u'PERKINSP40P3', 'sourceType': u'generator', 'value': [0, 0, 0], 'configID_FK': u''}, {'sourceName': u'EKODISCO', 'sourceType': u'grid', 'value': [0, 230.0, 230.0], 'configID_FK': u''}], 'Type': '1', 'id': 'B8:27:EB:26:8F:40', 'timeTodaySource': [{'sourceName': u'MUST4024C', 'sourceType': u'inverter', 'configID_FK': u'G1OKQR2XWWH5DZFY3Z4MCUTXIAEZ1OJF', 'timeToday': 5.5860077959961485}, {'sourceName': u'PERKINSP40P3', 'sourceType': u'generator', 'configID_FK': u'G1OKQR2XWWH5DZFY3Z4MCUTXIAEZ1OJF', 'timeToday': 0}, {'sourceName': u'EKODISCO', 'sourceType': u'grid', 'configID_FK': u'G1OKQR2XWWH5DZFY3Z4MCUTXIAEZ1OJF', 'timeToday': 12.221057193213047}], 'current': [{'sourceName': u'MUST4024C', 'sourceType': u'inverter', 'value': [5.012, 0, 0], 'configID_FK': u''}, {'sourceName': u'PERKINSP40P3', 'sourceType': u'generator', 'value': [0.0, 0.0, 0.1432], 'configID_FK': u''}, {'sourceName': u'EKODISCO', 'sourceType': u'grid', 'value': [0.2864, 5.012, 34.88352], 'configID_FK': u''}], 'time': '2017-07-15T19:23:05.125+0100', 'powerfactor': [{'sourceName': u'MUST4024C', 'sourceType': u'inverter', 'value': [0.8, 0, 0], 'configID_FK': u''}, {'sourceName': u'PERKINSP40P3', 'sourceType': u'generator', 'value': [0, 0, 0], 'configID_FK': u''}, {'sourceName': u'EKODISCO', 'sourceType': u'grid', 'value': [0, 0.8, 0.8], 'configID_FK': u''}], 'costTodaySource': [{'sourceName': u'MUST4024C', 'costToday': 0.0, 'sourceType': u'inverter', 'configID_FK': u''}, {'sourceName': u'PERKINSP40P3', 'costToday': 70.80287430187066, 'sourceType': u'generator', 'configID_FK': u''}, {'sourceName': u'EKODISCO', 'costToday': 1553.0768636886207, 'sourceType': u'grid', 'configID_FK': u''}]}], 'master': {'configuration_IDs': [u''], 'id': 'B8:27:EB:26:8F:40', 'time': '2017-07-15T19:23:05.125+0100'}}

try:
    avroProducer = AvroProducer({'bootstrap.servers': 'idarlington.local', 'schema.registry.url': 'http://idarlington.local:8081'},  default_value_schema=schema)
    avroProducer.produce(topic='gritServer', value=value)
except Exception,e:
    print str(e)
```
This works when producing from an ubuntu desktop or laptop.

This is the consumer:

```
from confluent_kafka import KafkaError
from confluent_kafka.avro import AvroConsumer
from confluent_kafka.avro.serializer import SerializerError

c = AvroConsumer({'bootstrap.servers': 'idarlington.local,', 'group.id': 'my_group', 'schema.registry.url': 'http://idarlington.local:8081'})
c.subscribe(['gritServer'])
running = True
while running:
    try:
        msg = c.poll(10)
        if msg:
            if not msg.error():
                print(msg.value())
            elif msg.error().code() != KafkaError._PARTITION_EOF:
                print(msg.error())
                running = False
    except SerializerError as e:
        print("Message deserialization failed for %s: %s" % (msg, e))
        running = False
        
c.close()
```

This works when producing from an ubuntu desktop or laptop.

**Comment by edenhill** [comment] 2017-07-15 10:15
Ah, I wanted that debug config on the Consumer, because that's where you were seeing the problems, right?

For your Consumer code: it looks good apart from setting `running` to False when PARTITION_EOF is reached: if your topic has multiple partitions and the consumer is subscribed to more than one, it will exit as soon as it reaches the end of any partition, regardless of remaining messages in the other partitions (this same behaviour is in the README example and should be fixed).
Also make sure to set `'default.topic.config': {'auto.offset.reset': 'smallest'}` to make sure your consumer starts from the beginning, and if you run it consecutively you might want to use a unique group.id for each run to prevent it from picking up committed offsets.

**Comment by darrenallen85** [comment] 2017-07-16 03:36
Hi @edenhill I am having what looks like the same issue : Running landoop fast-data-dev in docker container.

steps to recreate : 
1. run container using start_kafka.sh
2. create a new topic ( darren ) using : create_topic.sh
3. browse to localhost:3030 ... should see topic in topic browser, check schema registry - no schema for darren-key or darren-value
4. from host: python producer.py .... seems to work , check schema registry .. darren-key, darren-value now exist. Browse topic - no data. 

many thanks for looking at this  


[python_kafka_avro_test.zip](https://github.com/confluentinc/confluent-kafka-python/files/1150818/python_kafka_avro_test.zip)

**Comment by darrenallen85** [comment] 2017-07-16 03:36
btw - fair warning ... am complete n00b and may've made a stupid mistake

**Comment by darrenallen85** [comment] 2017-07-16 07:21
ok - maybe this could be called a bug in my code ... adding the following line instead of the sleep makes everything happy.

 avroProducer.flush()

**Comment by darrenallen85** [comment] 2017-07-16 07:21
@edenhill if this is intended behaviour its possibly worth updating the example ?

**Comment by darrenallen85** [comment] 2017-07-16 07:22
anyways - thanks to all who contribute to this project .. its awesome

**Comment by edenhill** [comment] 2017-07-18 07:31
Thanks, updated!

**Closed** 2017-07-18 07:30 UTC

**Comment by edenhill** [comment] 2017-07-18 09:24
It looks like it is stuck fetching topic test partition 0 at offset 0.
Are there messages in that partition?
Can you enable `"debug": "protocol,topic,fetch,cgrp,msg"` and see if anything interesting is showing up between the "FETCH" lines?

**Comment by idarlington** [comment] 2017-07-18 09:27
@edenhill 

 The consumer is on my machine and I am sending messages from the pi.

**Comment by edenhill** [comment] 2017-07-18 09:30
Okay, so do you have a problem with the producer or the consumer?

**Comment by idarlington** [comment] 2017-07-18 09:33
The producer

**Comment by edenhill** [comment] 2017-07-18 09:34
Did you add the avroProducer.flush() call?

**Comment by idarlington** [comment] 2017-07-18 09:36
No, I didnt

**Comment by edenhill** [comment] 2017-07-18 09:40
The produce() call is asynchronous, it will enqueue the message for transmission but the actual transmission to broker happens from a background thread.

You need to use flush() before exiting your program (or destroying the producer) to make sure outstanding messages are delivered.

For continually running producers you'll want to call poll() instead.

**Comment by idarlington** [comment] 2017-07-18 10:34
@edenhill Yeah, it worked. 

That is surprising. Can you share me a link to this or explain a bit more.

**Comment by edenhill** [comment] 2017-07-25 07:38
http://docs.confluent.io/current/clients/producer.html#asynchronous-writes
