### ISSUE TITLE
pip installation fails on python 3.8 (windows 10 enterprise)

### ISSUE THREAD

**Issue by dingobar** [confluentinc/confluent-kafka-python#866] opened 2020-05-15 06:24 UTC
Description
===========
The installation fails when Visual Studio Build Tools 2019 tries to build I guess? I thought the librdkafka was pre-build in the binaries but I guess not? Or is there something else up here?

I cannot use this package with python 3.8 before this is resolved sadly...

Pip installing works fine when done in a docker container running ubuntu 20.04.

```bash
    C:\Users\username\AppData\Local\Temp\pip-install-zh3stp7d\confluent-kafka\confluent_kafka\src\confluent_kafka.h(22): fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

How to reproduce
================

```python
pip install confluent-kafka # on a windows machine and in a py3.8 virtualenv
```

Attached log file of the installation.
[console_output.log](https://github.com/confluentinc/confluent-kafka-python/files/4632607/console_output.log)

Checklist
=========
Please provide the following information:

 - [x] Operating system: Windows 10 Enterprise
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [x] Critical issue

**Comment by ofek** [comment] 2020-05-15 16:52
@edenhill @rnpridgeon Hello! Are there plans to ship Windows binary wheels for Python 3.8 soon?

**Comment by matthew-d-jones** [comment] 2020-05-18 11:12
Duplicate of #753

**Comment by mhowlett** [comment] 2020-06-15 04:13
closing as duplicate - thanks for raising. have noted this internally as it keeps coming up.

**Closed by mhowlett** 2020-06-15 04:13 UTC
