### ISSUE TITLE
Stored offsets sometimes not reset after re-assignment.

### ISSUE THREAD

**Issue by venthur** [confluentinc/confluent-kafka-python#700] opened 2019-10-22 14:20 UTC
Description
===========

Sometimes after a re-assignment, a consumer (with  `'enable.auto.commit': False`), commits an offset that it consumed **before** the re-assignment.

How to reproduce
================
A dozen instances of the following program run in parallel. Since they use the same `TOPICS` we see the expected (re-)assignments at the beginning or the program. After some time we notice that some data is missing in the Database as if they haven't been persisted. 

Investigating the logs and the reported offsets from all running instances we noticed some jumps. Given the logs the following seems to happen:
* A consumer consumed a lot of messages of a partition **without** committing yet
* Re-Assignment happens and the consumer gets the **same** partition from which it already consumed (w/o committing) -- in fact the logger that reports the committed offset of the new assignment reports correctly an offset of `0`
* on the `revoke_callback`, we therefore reset our internal queues-to-be-persisted. We assume that technically the assignment has been removed and newly created so it should read from the latest **committed** offset...
* However, the next time we call `commit` we suddenly seem to commit the offset that this consumer has seen **before** the re-assignment, although we haven't consumed those messages since the new assignments yet. Those messages are "forever" gone.

Here's the (shortened) code that we use. Some things to notice:

* we use the `roundrobin` strategy
* `enable.auto.commit = False` since we want to commit manually only if we persisted successfully

I assume there is some race condition, because it happens often but not always.

```python
TOPICS = [...]  # big list of topics (~30 partitions)


logger = logging.getLogger(__name__)

def persist_pending_rows():
    # persist rows to DB or throw an exception

def queue(msg):
    # handle message (no persistence yet!)

def reset_handlers():
    # reset handlers

def revoke_callback(consumer, partitions):
    logger.info('Rebalancing! Resetting handlers.')
    # reset the internal state of the handlers
    for _, handler in TOPIC_HANDLERS.items():
        reset_handlers()
    # pending rows is now invalid, but that's not critical


def assign_callback(consumer, partitions):
    logger.info('(Re-)Assigning partitions!')
    partitions = consumer.committed(partitions)
    for part in partitions:
        logger.debug(f'Offset for {part.topic} {part.partition}:'
                     f' {part.offset}')


def main():

    client = AvroConsumer({
        'bootstrap.servers': config.BOOTSTRAP_SERVERS,
        'schema.registry.url': config.SCHEMA_REGISTRY_URL,
        'group.id': config.CONSUMER_GROUP,
        'auto.offset.reset': 'earliest',
        # do not automatically commit offsets to kafka, this relies on
        # on using consumer.commit() and having stable consumer group
        # names
        'enable.auto.commit': False,
        'partition.assignment.strategy': 'roundrobin',
    })
    client.subscribe(TOPICS,
                     on_revoke=revoke_callback,
                     on_assign=assign_callback)

    last_write = time.time()
    pending = 0
    while True:

        msg = client.poll(1.0)

        if msg is None:
            continue

        if msg.error():
            logger.warning(f'Kafka error {msg.error().code()}: {msg.error()}')
            continue

        # if we are here, we have an actual message
        (topic, payload, key) = msg.topic(), msg.value(), msg.key()
        resulting_rows = queue(msg)
        pending += resulting_rows

        # after 20mins or 200.000 rows persist and commit
        if (pending >= config.MAX_QUEUED_OBJECTS or
                time.time() - last_write > config.TIMEOUT_BEFORE_WRITING):

            persist_pending_rows()

            # commit to kafka if and only if the persist above was successful
            client.commit()

            partitions = self.consumer.assignment()
            partitions = self.consumer.committed(partitions)
            for part in partitions:
                logger.debug(f'Offset for {part.topic} {part.partition}:'
                             f' {part.offset}')

            pending = 0
            last_write = time.time()


if __name__ == '__main__':
    main()
```       

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.2.0', 16908288) and ('1.2.0', 16908543)
 - [x] Apache Kafka broker version: 2.2.1
 - [x] Client configuration: see above
 - [x] Operating system: debian/linux
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by venthur** [comment] 2019-10-23 08:49
I think we narrowed it down a bit more:
* A consumer consumed `n` messages without explicitly `committing` the offset
* A partition re-assignment happens and the consumer gets the **same** partion
* Within **milliseconds** after the assignment we do a commit -- this time we do it **synchronously** to check the returned offsets
* we see that the old offset `n` from before the re-assignment was committed

We don't use any threading, but again multiple instances of the same program in parallel.

Our assumption is now that the internal offset store is not reset quickly enough during re-assignment so we still commit the old contents of the store. If we try to reproduce it manually, we can't, probably we're too slow.

We notice this behavior in ~10% of the re-assignments (e.g. 10 out of 100 re-assignments within 12hrs, and 19 consumers in the consumer group.)

**Comment by rnpridgeon** [comment] 2019-10-25 11:47
I suggest ditching the `commit ` API in favor of `store_offsets` with`enable.auto.offset.store=False`. With `enable.auto.offset.store=True`(default) the client will automatically store the offset+1 of the message just prior to passing the message to your application. If you use the `store_offsets` API however you have control over the internal commit store while still taking advantage of `enable.auto.commit`. 

https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.store_offsets

https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management

**Comment by jacopofar** [comment] 2019-10-26 09:52
I find it a bit confusing, I would expect to set `enable.auto.commit` to `False` to manage offsets myself and to `True` to let the client commit them automatically when the application consumes.

Is it the expected behavior that when a partition is revoked or assigned the client receives the assignment offset from the broker (that can be seen calling `assignment()`) but doesn't resets the offsets in the internal store so when committing the old value is sent instead?

**Comment by rnpridgeon** [comment] 2019-12-17 14:43
There are actually two distinct operations going on here. 

1. Committing offsets to kafka (a global cache of sorts)
2. Storing the offset to be committed.  

Keeping auto offset commit enabled satisfies item 1. This ensures your local offset store will be propagated to kafka when a rebance happens, a consumer is closed and/or the commit interval has elapsed. 

The default behavior,  which emulates the java client, is to store the offset locally for commit the second ownership of the message transfers from the library to your application. This is because message handling is no longer in the libraries control. Librdkafka derived clients expose this internal store to your application. This gives the application fine-grained control over the local offset store, so it can decided what will be propagated without having to worry about when.

**Closed** 2021-01-26 15:04 UTC
