### ISSUE TITLE
confluent-kafka not installing in Python 3.8

### ISSUE THREAD

**Issue by dineshTivo** [confluentinc/confluent-kafka-python#889] opened 2020-05-31 16:35 UTC
Description
===========
When try to install confluent-kafka through _python -m pip install confluent-kafka_ command in windows 10 for Python 3.8, getting below error message whereas it was installed successfully in Python 3.7.

Note: Wheel file not available for Python 3.8 Windows build in https://pypi.org/project/confluent-kafka/#files

_creating build\temp.win32-3.8\Release\Users\dprabhu\AppData\Local\Temp\pip-install-zghtb4kp\confluent-kafka\confluent_kafka\src
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Python38-32\include" "-IC:\Program Files (x86)\Python38-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /TcC:\Users\dprabhu\AppData\Local\Temp\pip-install-zghtb4kp\confluent-kafka\confluent_kafka\src\confluent_kafka.c /Fobuild\temp.win32-3.8\Release\Users\dprabhu\AppData\Local\Temp\pip-install-zghtb4kp\confluent-kafka\confluent_kafka\src\confluent_kafka.obj
  confluent_kafka.c
  c:\users\dprabhu\appdata\local\temp\pip-install-zghtb4kp\confluent-kafka\confluent_kafka\src\confluent_kafka.h(22): fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2_
  ----------------------------------------
  ERROR: Failed building wheel for confluent-kafka

How to reproduce
================

 _python -m pip install confluent-kafka_ command in windows 10 for Python 3.8

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.4.2
 - [ ] Apache Kafka broker version: 
 - [ ] Client configuration: `{...}`
 - [] Operating system: Windows 10
 - [ ] Provide client logs (with `'debug': '..'` as necessary): 
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Python38-32\include" "-IC:\Program Files (x86)\Python38-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /TcC:\Users\dprabhu\AppData\Local\Temp\pip-install-zghtb4kp\confluent-kafka\confluent_kafka\src\confluent_kafka.c /Fobuild\temp.win32-3.8\Release\Users\dprabhu\AppData\Local\Temp\pip-install-zghtb4kp\confluent-kafka\confluent_kafka\src\confluent_kafka.obj
  confluent_kafka.c
  c:\users\dprabhu\appdata\local\temp\pip-install-zghtb4kp\confluent-kafka\confluent_kafka\src\confluent_kafka.h(22): fatal error C1083: Cannot open include file: 'librdkafka/rdkafka.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mparry** [comment] 2020-06-05 12:18
See #753

**Comment by mhowlett** [comment] 2020-06-15 03:59
thanks @mparry - closing as duplicate of #753 
(yes we want to do this).

**Closed by mhowlett** 2020-06-15 03:59 UTC
